GET http://localhost:3001/account/allData

###

POST http://localhost:3001/account/create
Content-Type: application/json

{
    "username": "bellybell",
    "email": "belliestbell@bella.com",
    "password": "bellybobell"
}

###

# DELETE http://localhost:3001/account/delete/64b1dd8b32243b9b9f8871df

###

GET http://localhost:3001/account/login/af@adsf.edu/ab

###

# PATCH http://localhost:3001/account/update/64b1dd8b32243b9b9f8871df
# Content-Type: application/json

# {
#     "balance": 123
# }

PATCH http://localhost:3001/account/update/Bella@mit.edu/10

###

GET http://localhost:3001/account/transfer/Bella@mit.edu